Create console interface for script
minskpython/pyvideo_scrape_mpm pull request #10
Opened 2020-07-06 20:15 UTC by JuliusChrona

2020-07-07 17:18 UTC, shurph commented
Спасибо за PR! Это классно, что кто-то взялся поддерживать эту инициативу!

Сейчас посмотрю, что тут можно улучшить.

2020-07-07 18:46 UTC, kai3341 requested changes

2020-07-07 18:46 UTC, kai3341 commented on arg_interface.py
> +                        )
И в чём проблема была сделать по PEP8?
```
    parser.add_argument(
        '-f', '--file',
        help='Use your own file with urls',
        action='store',
        default='urls.list',
        metavar='file',
    )
```
Обрати также внимание на trailing-запятую в последней строке -- поставь её

2020-07-07 18:46 UTC, kai3341 commented on scrape.py
> +    list_filename, FOLDER_NAME = setup_interface()
У меня после celery (а там такгого хватает) осталось послевкусие. Ок, ты понял, что тебе нужна setup-функция. Такде ты пришёл к тому, что она возвращает несколько значений. Здесь сразу надо остановиться. Сделай через класс. Примерно так:

```
class Scrape:
    def __init__(self):
        ...

    def setup(self):
        ...

    def main(self):
        ...

    @classmethod
    def execute(cls):
        self = cls()
        return self.main()

if __name__ == '__main__':
    Scrape.execute()
```

2020-07-07 19:09 UTC, shurph requested changes
Оставил несколько комментариев по коду. Было бы классно внести исправления!

2020-07-07 19:09 UTC, miksask commented on requirements.txt
> +flake8
тут лучше было бы разделить на два файла: 
- requirements.txt - там всё, что нужно для работы скрипта
- requirements-dev.txt - там всё то, что дополнительно нужно для разработки (flake8, pylint, ещё что-то)

вообще, по идее, это изменение лучше в рамках PR #9 сделать

2020-07-07 19:09 UTC, miksask commented on scrape.py
> +# DEFAULT_URLS_LIST_FILENAME = "urls.list"
Лучше сразу выкашивать заменённые переменные, не оставлять их на потом

2020-07-07 19:09 UTC, miksask commented on scrape.py
> +# DEFAULT_SILENT_MODE = False
Если мне не изменяет память, я в итоге отказался от silent mode, можно выкашивать

2020-07-07 19:09 UTC, miksask commented on scrape.py
> +        sys.stdout = open(os.devnull, "w")  # output => null
вообще, тут предполагалось, что не только stdout, но и stderr будет подавляться.

2020-07-07 19:09 UTC, miksask commented on scrape.py
> +        sys.stdout = open(os.devnull, "w")  # output => null
но, мне кажется, от silent mode лучше вообще пока что отказаться

2020-07-07 19:09 UTC, miksask commented on scrape.py
> +    return URLS_LIST_FILENAME, FOLDER_NAME
Возможно, здесь лучше отдавать namespace полностью?

Если количество аргументов будет увеличиваться, то кортеж будет расширяться, и придётся везде менять способ использования функции

2020-07-07 19:09 UTC, miksask commented on arg_interface.py
> +import argparse
не очень уверен, что стоит пока что выделять в отдельный файл инициализацию парсера аргументов

2020-07-08 14:49 UTC, kai3341 approved these changes

2020-07-14 10:04 UTC, shurph approved these changes
lgtm

2020-07-15 13:34 UTC, merged